# Generated by Django 4.2.4 on 2023-08-21 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date_time',
        ),
    ]
